CREATE EXTENSION IF NOT EXISTS POSTGIS;

CREATE TABLE IF NOT EXISTS SEARCH_EVENTS ( 
    ID SERIAL PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    SEARCH_QUERY VARCHAR(100),
    LATITUDE DOUBLE PRECISION NOT NULL,
    LONGITUDE DOUBLE PRECISION NOT NULL,
    H3_INDEX VARCHAR(15),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    GEOM GEOMETRY(POINT, 4326) 
);

CREATE TABLE IF NOT EXISTS RESTAURANTES ( 
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    RATING NUMERIC(2,1),
    LATITUDE DOUBLE PRECISION NOT NULL,
    LONGITUDE DOUBLE PRECISION NOT NULL,
    H3_INDEX VARCHAR(15),
    GEOM GEOMETRY(POINT, 4326)
);

CREATE TABLE IF NOT EXISTS demand_logs (
    id SERIAL PRIMARY KEY,
    region VARCHAR(50),
    demand INT,
    timestamp BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION update_geom()
RETURNS TRIGGER AS $$
BEGIN
    NEW.GEOM = ST_SetSRID(ST_MakePoint(NEW.LONGITUDE, NEW.LATITUDE), 4326);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trg_search_events_geom
BEFORE INSERT OR UPDATE ON SEARCH_EVENTS
FOR EACH ROW EXECUTE FUNCTION update_geom();

CREATE OR REPLACE TRIGGER trg_restaurants_geom
BEFORE INSERT OR UPDATE ON RESTAURANTES
FOR EACH ROW EXECUTE FUNCTION update_geom();